<a href="https://colab.research.google.com/github/bharathraj1924/Data-Science-/blob/main/TASK_1_NUMPY_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

important NumPy Functions

Mathematical functions

In [ ]:
import numpy as np
my_array = np.array([0,1,2,3,4,5])
sum_of_elements = np.sum(my_array)
print(sum_of_elements)

15


In [ ]:
my_array = np.array([0,1,2,3,4,5])
mean_of_elements = np.mean(my_array)
print (mean_of_elements)

2.5


In [ ]:
my_array = np.array([0,1,2,3,4,5])
median_of_elements = np.median(my_array)
print(median_of_elements)

2.5


In [ ]:
my_array = np.array([0,1,2,3,4,5])
std_of_elements = np.std(my_array)
print (std_of_elements)

1.707825127659933


In [ ]:
my_array = np.array([0,1,2,3,4,5])
min_of_elements = np.min(my_array)
print (min_of_elements)

0


In [ ]:
my_array = np.array([0,1,2,3,4,5])
max_of_elements = np.max(my_array)
print (max_of_elements)

5


Array Manipulation

In [ ]:

import numpy as np
original_array = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_array = np.reshape(original_array, (3, 2))
print(reshaped_array)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
concatenated_array = np.concatenate((array1,array2))
print(concatenated_array)

[1 2 3 4 5 6]


In [ ]:
original_array = np.array([1,2,3,4,5,7,8,9,10])
split_array = np.split(original_array,3)
print (split_array)

[array([1, 2, 3]), array([4, 5, 7]), array([ 8,  9, 10])]


In [ ]:
original_array = np.array([[1,2,3],[4,5,6]])
transposed_array = np.transpose(original_array)
print (transposed_array)

[[1 4]
 [2 5]
 [3 6]]


Array Operations

In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
result_array = np.add(array1,array2)
print (result_array)

[5 7 9]


In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
result_array = np.subtract(array1,array2)
print (result_array)

[-3 -3 -3]


In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
result_array = np.multiply(array1,array2)
print (result_array)

[ 4 10 18]


In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
result_array = np.divide(array1,array2)
print (result_array)

[0.25 0.4  0.5 ]


In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
result_array = np.dot(array1,array2)
print (result_array)

32


Trigonometry functions

In [ ]:
angles = np.array([0,np.pi/2,np.pi])
sine_values = np.sin(angles)
print (sine_values)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [ ]:
angles = np.array([0,np.pi/2,np.pi])
cosine_values = np.cos(angles)
print (cosine_values)

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [ ]:
angles = np.array([0,np.pi/2,np.pi])
tangent_values = np.tan(angles)
print (tangent_values)

[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
sin_values = np.array([0,9,8,7])
angles = np.arcsin(sin_values)
print (angles)

[ 0. nan nan nan]


<ipython-input-36-b8a5a1cb635f>:2: RuntimeWarning: invalid value encountered in arcsin
  angles = np.arcsin(sin_values)


In [ ]:
import numpy as np
cos_values = np.array([1, 0.5, 0, -0.5, -1])
angles = np.arccos(cos_values)
print("Cosine values:", cos_values)
print("Corresponding angles (in radians):", angles)


Cosine values: [ 1.   0.5  0.  -0.5 -1. ]
Corresponding angles (in radians): [0.         1.04719755 1.57079633 2.0943951  3.14159265]


In [ ]:
import numpy as np
tan_values = np.array([0, 1, -1, np.sqrt(3), -np.sqrt(3)])
angles = np.arctan(tan_values)
print("Tangent values:", tan_values)
print("Corresponding angles (in radians):", angles)


Tangent values: [ 0.          1.         -1.          1.73205081 -1.73205081]
Corresponding angles (in radians): [ 0.          0.78539816 -0.78539816  1.04719755 -1.04719755]


Random

In [ ]:
import numpy as np
random_array = np.random.rand(5)
print("Random array:", random_array)


Random array: [0.81607215 0.59455347 0.07794015 0.69293444 0.45121858]


In [ ]:
import numpy as np
random_array = np.random.randn(5)
print("Random array from standard normal distribution:", random_array)


Random array from standard normal distribution: [ 0.1955169  -1.10673799 -0.3493681  -0.3952131   0.44947484]


In [ ]:
import numpy as np
random_integer = np.random.randint(0, 10)
print("Random integer:", random_integer)


Random integer: 9


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
np.random.shuffle(arr)
print("Shuffled array:", arr)


Original array: [1 2 3 4 5]
Shuffled array: [2 1 3 4 5]


In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
print("Data:", data)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Data: [ 1  2  3  4  5  6  7  8  9 10]
25th Percentile: 3.25
75th Percentile: 7.75


In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 1, 5, 7])
correlation_matrix = np.corrcoef(x, y)
print("Array x:", x)
print("Array y:", y)
print("Correlation matrix:")
print(correlation_matrix)


Array x: [1 2 3 4 5]
Array y: [2 4 1 5 7]
Correlation matrix:
[[1.        0.7284928]
 [0.7284928 1.       ]]


Logic Operations

In [ ]:
import numpy as np

arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])
result = np.logical_and(arr1, arr2)
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Logical AND result:", result)


Array 1: [ True  True False False]
Array 2: [ True False  True False]
Logical AND result: [ True False False False]


In [ ]:
import numpy as np

arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])
result = np.logical_or(arr1, arr2)
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Logical OR result:", result)


Array 1: [ True  True False False]
Array 2: [ True False  True False]
Logical OR result: [ True  True  True False]


In [ ]:
import numpy as np
arr = np.array([True, False, True, False])
result = np.logical_not(arr)
print("Original array:", arr)
print("Logical NOT result:", result)


Original array: [ True False  True False]
Logical NOT result: [False  True False  True]



Linear Algebra

In [ ]:
import numpy as np
matrix = np.array([[4, 7],
                   [2, 6]])
inverse_matrix = np.linalg.inv(matrix)
print("Original matrix:")
print(matrix)
print("Inverse matrix:")
print(inverse_matrix)


Original matrix:
[[4 7]
 [2 6]]
Inverse matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [ ]:
import numpy as np
matrix = np.array([[4, 7],
                   [2, 6]])
determinant = np.linalg.det(matrix)
print("Original matrix:")
print(matrix)
print("Determinant:", determinant)


Original matrix:
[[4 7]
 [2 6]]
Determinant: 10.000000000000002


In [ ]:
import numpy as np
matrix = np.array([[4, 7],
                   [2, 6]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Original matrix:")
print(matrix)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Original matrix:
[[4 7]
 [2 6]]
Eigenvalues:
[1.12701665 8.87298335]
Eigenvectors:
[[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]


Sorting

In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
sorted_arr = np.sort(arr)
print("Original array:", arr)
print("Sorted array:", sorted_arr)


Original array: [3 1 4 1 5 9 2 6 5 3 5]
Sorted array: [1 1 2 3 3 4 5 5 5 6 9]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
np.save('saved_array.npy', arr)

In [ ]:
import numpy as np
loaded_arr = np.load('saved_array.npy')
print("Loaded array:", loaded_arr)


Loaded array: [1 2 3 4 5]


Creating Arrays

In [ ]:
import numpy as np
arr1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1d)


1D array: [1 2 3 4 5]


In [ ]:
arr1d = np.zeros(5)
print("1D array with zeros:", arr1d)


1D array with zeros: [0. 0. 0. 0. 0.]


In [ ]:
arr1d = np.ones(5)
print("1D array with ones:", arr1d)

1D array with ones: [1. 1. 1. 1. 1.]


In [ ]:
import numpy as np
arr1d = np.arange(5)
print("1D array:", arr1d)
arr1d_step = np.arange(2, 10, 2)
print("1D array with step 2:", arr1d_step)
arr1d_float = np.arange(0, 1, 0.1)
print("1D array with step 0.1:", arr1d_float)

1D array: [0 1 2 3 4]
1D array with step 2: [2 4 6 8]
1D array with step 0.1: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
arr1d = np.linspace(0, 1, 5)
print("1D array:", arr1d)
arr1d_custom_range = np.linspace(2, 5, 10)
print("1D array with custom range:", arr1d_custom_range)
arr1d_pi = np.linspace(0, 2 * np.pi, 20)
print("1D array with values from 0 to 2*pi:", arr1d_pi)

1D array: [0.   0.25 0.5  0.75 1.  ]
1D array with custom range: [2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]
1D array with values from 0 to 2*pi: [0.         0.33069396 0.66138793 0.99208189 1.32277585 1.65346982
 1.98416378 2.31485774 2.64555171 2.97624567 3.30693964 3.6376336
 3.96832756 4.29902153 4.62971549 4.96040945 5.29110342 5.62179738
 5.95249134 6.28318531]


In [ ]:
identity_int = np.eye(4, dtype=int)
print("\n4x4 Identity matrix with integers:")
print(identity_int)


4x4 Identity matrix with integers:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Array Information

In [ ]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array shape:", arr_1d.shape)

1D array shape: (5,)


In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("Number of dimensions for arr_1d:", arr_1d.ndim)

Number of dimensions for arr_1d: 1


In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("Size of arr_1d:", arr_1d.size)

Size of arr_1d: 5


In [ ]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
data_type = my_array.dtype

print("Data type of array elements:", data_type)


Data type of array elements: int64
